package com.onegateafrica.entity;

public enum roles {
  PNEUMOLOGY,PSYCHIATRY,RADIOLOGY,RADIOTHERAPY,RHEUMATOLOGY,UROLOGY,
  ODONTOLOGY,ONCOLOGY,OBSTETRICS,OPHTHALMOLOGY,ORTHOPEDICS,ENT_RHINO_LARYNGOLOGY,
  PEDIATRICS,PHYSICAL,PREVENTIVE,NEONTOLOGY,NEPHROLOGY,
  ALLERGOLOGY,ANESTHESIOLOGY,ANDROLOGY,CARDIOLOGY,HEART_SURGERY,
  PLASTIC_AND_RECONSTRUCTIVE_SURGERY,GENERAL_SERGERY,MAXILLOFACIAL_SERGERY,
  PEDIATRIC_SERGERY,THORACIC_SERGERY,VASCULAR_SERGERY,NEUROSURGERY,DERMATOLOGY,
  ENDOCRINOLOGY,GASTROENTEROLOGY,GERIATRICS,GYNECOLOGY,HEMATOLOGY,HEPATOLOGY,
  INFECTIOUS_DISEASE,ACUTE_MEDICINE,OCCUPATIONAL,
  PALLIATIVE_MEDICINE,FORMATEUR,NURSE,PARAMED
}
